#!/usr/bin/env bash
# EduTrack - InfinityFree deployment
# Mirrors the project into the hosting account's htdocs over FTP and writes
# api/config.local.php with the production database credentials.
#
# Usage:
#   ./deploy.sh
#
# Non-interactive (everything from the environment):
#   FTP_HOST=ftp.example.com FTP_USER=... FTP_PASS=... \
#   DB_HOST=sql204.infinityfree.com DB_NAME=... DB_USER=... DB_PASS=... ./deploy.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ask() {
  local var="$1" prompt="$2" hidden="${3:-no}"
  if [ -z "${!var:-}" ]; then
    if [ "$hidden" = "hidden" ]; then
      read -r -s -p "$prompt: " value; echo
    else
      read -r -p "$prompt: " value
    fi
    printf -v "$var" '%s' "$value"
  fi
}

ask FTP_HOST  "FTP host (from control panel > Account Details)"
ask FTP_USER  "FTP user"
ask FTP_PASS  "FTP password" hidden
ask DB_HOST   "MySQL host (sqlXXX.infinityfree.com)"
ask DB_NAME   "MySQL database"
ask DB_USER   "MySQL user"
ask DB_PASS   "MySQL password" hidden

[ -n "$FTP_HOST" ] || { echo "[error] FTP host is empty" >&2; exit 1; }

FTP_HOST="${FTP_HOST#ftp://}"
FTP_HOST="${FTP_HOST%/}"

# Connectivity check: refuse to start a 34MB upload that cannot succeed.
if ! timeout 15 bash -c "echo > /dev/tcp/${FTP_HOST%%:*}/21" 2>/dev/null; then
  echo "[error] cannot reach ${FTP_HOST%%:*}:21" >&2
  echo "        Check the FTP host name in the control panel (it is usually" >&2
  echo "        ftp.<your-account-subdomain>.infinityfreeapp.com, not your" >&2
  echo "        own domain). Also check your firewall / ISP." >&2
  exit 1
fi

TMP_CONFIG="$(mktemp)"
SKIPPED_FILE="$(mktemp)"
trap 'rm -f "$TMP_CONFIG" "$SKIPPED_FILE"' EXIT
: > "$SKIPPED_FILE"
cat > "$TMP_CONFIG" <<PHPCONF
<?php
/**
 * Production (InfinityFree) database overrides.
 * Generated by deploy.sh on $(date -u '+%Y-%m-%d %H:%M:%S') UTC.
 */
if (!defined('EDUTRACK_DB_CONFIG')) {
    define('EDUTRACK_DB_CONFIG', [
        'host' => '${DB_HOST}',
        'port' => '3306',
        'name' => '${DB_NAME}',
        'user' => '${DB_USER}',
        'pass' => '${DB_PASS}',
    ]);
}
PHPCONF

# InfinityFree enforces a per-file size limit on the filesystem, not just on
# upload, and anything over it is deleted without an error being reported.
# The limits differ by type, so a single flat threshold silently loses files.
size_limit_for() {
  case "$1" in
    *.html|*.htm|*.php|*.js) printf '1048576'   ;;  # 1 MB
    .htaccess)                printf '10240'     ;;  # 10 kB
    *)                        printf '10485760'  ;;  # 10 MB
  esac
}

# Everything in the web root except local-only tooling, the SQL dumps
# (never expose schema/seed data over HTTP) and the local dev config.
# Files over the host's limit are appended to $SKIPPED_FILE so every backend
# can exclude them explicitly instead of relying on the server to drop them.
upload_list() {
  find . -type f \
    ! -path './.git/*' \
    ! -path './database/*' \
    ! -name '*.sh' \
    ! -name 'README.md' \
    ! -name '*.zip' \
    ! -path './api/config.local.php' \
    ! -name '.env' \
    ! -path './node_modules/*' \
    -printf '%P\n' \
  | sort \
  | while IFS= read -r rel; do
      size=$(stat -c '%s' "$ROOT/$rel")
      limit=$(size_limit_for "$rel")
      if [ "$size" -gt "$limit" ]; then
        printf '[skip] %s (%s bytes, limit %s for %s)\n' \
          "$rel" "$size" "$limit" "$(case "$rel" in *.html|*.htm|*.php|*.js) echo html/php/js;; .htaccess) echo htaccess;; *) echo other;; esac)" >&2
        printf '%s\n' "$rel" >> "$SKIPPED_FILE"
        continue
      fi
      printf '%s\n' "$rel"
    done
}

CRED="${FTP_USER}:${FTP_PASS}"
BASE="ftp://${FTP_HOST}"

UPLOAD_LIST="$(mktemp)"
trap 'rm -f "$TMP_CONFIG" "$SKIPPED_FILE" "$UPLOAD_LIST"' EXIT
upload_list > "$UPLOAD_LIST"

if [ -s "$SKIPPED_FILE" ]; then
  echo
  echo "[error] $(wc -l < "$SKIPPED_FILE") file(s) exceed the host's per-file limit"
  echo "        and WILL be deleted by the server if uploaded:"
  sed 's/^/          /' "$SKIPPED_FILE"
  echo
  echo "        Shrink or drop these before deploying, or they will 404."
  exit 1
fi

if command -v lftp >/dev/null 2>&1; then
  echo "[ftp] lftp backend"
  EXCLUDES=(
    --exclude-glob '*.sh'
    --exclude-glob 'README.md'
    --exclude-glob '*.zip'
    --exclude-glob 'database/*'
    --exclude-glob 'api/config.local.php'
    --exclude-glob '.git/*'
    --exclude-glob '.env'
    --exclude-glob 'node_modules/*'
  )
  lftp -u "${FTP_USER},${FTP_PASS}" "ftp://${FTP_HOST}" -e "
    set ftp:ssl-allow no;
    set ftp:passive-mode yes;
    set net:max-retries 3;
    set net:timeout 15;
    mirror -R --verbose --parallel=3 --delete ${EXCLUDES[*]} '${ROOT}' /htdocs;
    put '${TMP_CONFIG}' /htdocs/api/config.local.php;
    bye
  "
else
  echo "[ftp] curl backend (lftp not installed)"
  total=$(wc -l < "$UPLOAD_LIST")
  n=0
  while IFS= read -r rel; do
    n=$((n + 1))
    printf '\r[%d/%d] %s' "$n" "$total" "$rel"
    curl -sS --ftp-create-dirs -u "$CRED" -T "$ROOT/$rel" "$BASE/htdocs/$rel"
  done < "$UPLOAD_LIST"
  printf '\n'
  curl -sS --ftp-create-dirs -u "$CRED" -T "$TMP_CONFIG" "$BASE/htdocs/api/config.local.php"
fi

echo
echo "[done] $(wc -l < "$UPLOAD_LIST") files uploaded."
echo "Next: open  http://${FTP_HOST#ftp.}/api/stats.php"
